"""
FinSight Pro - Company Comparison Agent

Architecture

                User Query
                     │
         ┌───────────┴───────────┐
         │                       │
         ▼                       ▼
 Pipeline (Company A)     Pipeline (Company B)
         │                       │
         ▼                       ▼
     Investor Report       Investor Report
         └───────────┬───────────┘
                     ▼
             Comparison Agent
                     ▼
         Comparative Financial Report
"""

import logging
import os
import time

from dotenv import load_dotenv
from groq import RateLimitError
from langchain_groq import ChatGroq

from src.agents.orchestrator import run_pipeline

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(__name__)

MAX_COMPARE_CHARS = 12000

llm = ChatGroq(
    model=os.getenv("GROQ_MODEL", "llama-3.1-8b-instant"),
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=0.2,
)

COMPARE_PROMPT = """
You are FinSight Pro's Company Comparison Agent.

Your ONLY responsibility is to compare two investor reports.

The reports were generated by FinSight Pro's Research, Analysis,
and Report agents.

STRICT RULES

- Use ONLY information contained in the reports.
- Never introduce outside knowledge.
- Never invent financial metrics.
- Never change numerical values.
- Never modify percentages.
- Never alter currencies.
- Never rewrite market capitalization.
- Never assume missing information.
- Never interpret what financial metrics imply.
- Never infer future performance.
- Only summarize information explicitly present in the reports.
- If a metric is missing from one report, write "Not available in the provided report."
- Do not use placeholder values like N/A unless they already appear in the reports.
- Ensure the Overall Comparison is fully consistent with the Comparison Table.
- Do not contradict numerical values shown elsewhere in the report.
- Do NOT provide investment advice.

Company A ({ticker_a})

{report_a}

------------------------------------------------------------

Company B ({ticker_b})

{report_b}

------------------------------------------------------------

Write a comparison using EXACTLY this format.

Executive Summary

Comparison Table

Strengths

Risk Profile

Overall Comparison

Limitations

Keep the report under 250 words.
"""

def compare_companies(
    query: str,
    ticker_a: str,
    ticker_b: str,
) -> dict:
    """
    Compare two companies using the complete FinSight pipeline.

    Returns
    -------
    dict containing:

    success
    comparison
    report_a
    report_b
    comparison_latency
    total_latency
    """

    overall_start = time.perf_counter()

    logger.info(
        "Starting comparison | %s vs %s",
        ticker_a,
        ticker_b,
    )

    # --------------------------------------------------
    # Pipeline A
    # --------------------------------------------------

    result_a = run_pipeline(
        query=query,
        ticker=ticker_a,
    )

    if not result_a["success"]:
        logger.warning(
            "Comparison stopped because %s pipeline failed.",
            ticker_a,
        )

        return {
            "success": False,
            "stage": ticker_a,
            "message": result_a["message"],
        }

    # --------------------------------------------------
    # Pipeline B
    # --------------------------------------------------

    result_b = run_pipeline(
        query=query,
        ticker=ticker_b,
    )

    if not result_b["success"]:
        logger.warning(
            "Comparison stopped because %s pipeline failed.",
            ticker_b,
        )

        return {
            "success": False,
            "stage": ticker_b,
            "message": result_b["message"],
        }

    comparison_prompt = COMPARE_PROMPT.format(
        ticker_a=ticker_a,
        ticker_b=ticker_b,
        report_a=result_a["report"][:MAX_COMPARE_CHARS],
        report_b=result_b["report"][:MAX_COMPARE_CHARS],
    )

    comparison_start = time.perf_counter()

    try:

        response = llm.invoke(comparison_prompt)

        comparison_latency = round(
            time.perf_counter() - comparison_start,
            2,
        )

        comparison = response.content.strip()

        if not comparison:
            logger.warning("Comparison agent returned an empty response.")

            return {
                "success": False,
                "message": "Comparison agent returned an empty response.",
            }

        total_latency = round(
           result_a["total_latency"]
           + result_b["total_latency"]
           + comparison_latency,
           2,
        )

        logger.info(
            "Comparison completed | latency=%.2fs",
            total_latency,
        )

        return {
               "success": True,

               "ticker_a": ticker_a,
               "ticker_b": ticker_b,

               "report_a": result_a["report"],
                "report_b": result_b["report"],

               "report_a_latency": result_a["total_latency"],
                "report_b_latency": result_b["total_latency"],

               "comparison": comparison,

                "comparison_latency": comparison_latency,

                "total_latency": total_latency,
            }
    except RateLimitError:

        logger.warning("Comparison rate limit reached.")

        return {
            "success": False,
            "message":
                "Comparison is temporarily unavailable because the AI service rate limit has been reached.",
        }

    except Exception:

        logger.exception("Comparison failed.")

        return {
            "success": False,
            "message":
                "Unable to generate comparison due to an unexpected error.",
        }

def main():
    print("=" * 90)
    print("FinSight Pro - Company Comparison")
    print("=" * 90)

    while True:

        ticker_a = input("\nCompany A (or 'exit'): ").strip()

        if ticker_a.lower() == "exit":
            break

        ticker_b = input("Company B: ").strip()

        query = input("Comparison Question: ").strip()

        result = compare_companies(
            query=query,
            ticker_a=ticker_a,
            ticker_b=ticker_b,
        )

        print("\n" + "=" * 90)

        if not result["success"]:
            print("Comparison failed.")
            print(result["message"])
            continue

        print("COMPANY COMPARISON REPORT")
        print("=" * 90)
        print(result["comparison"])

        print("\nPerformance Summary")
        print("=" * 90)
        print(f"{result['ticker_a']} Pipeline : {round(result['report_a_latency'],2)} sec")
        print(f"{result['ticker_b']} Pipeline : {round(result['report_b_latency'],2)} sec")
        print(f"Comparison Agent : {result['comparison_latency']} sec")
        print("-" * 90)
        print(f"Total Pipeline   : {result['total_latency']} sec")
        print("=" * 90)




if __name__ == "__main__":
    main()    