"""
FinSight Pro - Research Agent

This module creates the AI financial research agent responsible for
reasoning about user questions and deciding which tools to invoke.

Current tools:
    • get_stock_snapshot
    • search_filings

Architecture
------------
User
   │
   ▼
Research Agent (LLM + Tool Calling)
   │
   ├──────────────┐
   ▼              ▼
Market Tool   Filing Tool
   │              │
   └──────┬───────┘
          ▼
     Final Answer
"""

from __future__ import annotations

import time
import logging
import os

from langchain.agents import create_agent
from langchain_groq import ChatGroq

from src.agents.tools import (
    get_stock_snapshot,
    search_filings,
)

from src.config import (
    GROQ_MODEL,
    GROQ_TEMPERATURE,
)

# ---------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------
# LLM
# ---------------------------------------------------------------------

llm = ChatGroq(
    model=GROQ_MODEL,
    temperature=GROQ_TEMPERATURE,
    groq_api_key=os.getenv("GROQ_API_KEY"),
)

# ---------------------------------------------------------------------
# System Prompt
# ---------------------------------------------------------------------

SYSTEM_PROMPT = """
You are FinSight Pro, an AI Financial Research Assistant.

Your primary objective is to provide accurate, grounded, and concise
financial research using ONLY the available tools.

You have access to two tools:

1. get_stock_snapshot
   Use this tool whenever the user asks about:
   - Current stock price
   - Market capitalization
   - P/E ratio
   - Recent stock performance
   - Live market information

2. search_filings
   Use this tool whenever the user asks about:
   - Revenue
   - Risks
   - Business segments
   - Products
   - Financial statements
   - Strategy
   - Competition
   - Management discussion
   - SEC filings

Rules:

• Always decide whether tools are needed before answering.

• If the question requires BOTH live market data and SEC filings,
  call BOTH tools.

• Never fabricate numbers.

• Never guess financial information.

• Use tool outputs as the source of truth.

• If a tool cannot answer, clearly explain the limitation.

• Produce one well-structured final response.

When both tools are used:

1. Summarize the market snapshot.
2. Summarize filing insights.
3. Finish with an integrated conclusion.
"""

# ---------------------------------------------------------------------
# Tool Registry
# ---------------------------------------------------------------------

TOOLS = (
    get_stock_snapshot,
    search_filings,
)

# ---------------------------------------------------------------------
# Research Agent
# ---------------------------------------------------------------------

research_agent = create_agent(
    model=llm,
    tools=TOOLS,
    system_prompt=SYSTEM_PROMPT,
)

# ---------------------------------------------------------------------
# Research API
# ---------------------------------------------------------------------



def run_research(
    query: str,
    ticker: str,
) -> str:
    """
    Run a financial research query using the AI agent.

    Parameters
    ----------
    query:
        User's financial question.

    ticker:
        Company ticker (e.g. AAPL).

    Returns
    -------
    str
        Final response generated by the agent.
    """

    ticker = ticker.strip().upper()

    prompt = (
        f"Company ticker: {ticker}\n\n"
        f"User Question:\n{query}"
    )

    logger.info("Starting research | ticker=%s", ticker)

    start = time.perf_counter()

    try:

        result = research_agent.invoke(
            {
                "messages": [
                    {
                        "role": "user",
                        "content": prompt,
                    }
                ]
            }
        )

        latency = time.perf_counter() - start

        logger.info(
            "Research completed | ticker=%s | latency=%.2fs",
            ticker,
            latency,
        )

        return result["messages"][-1].content

    except Exception:

        logger.exception(
            "Research failed for %s",
            ticker,
        )

        return "Unable to complete the research request."

    # ---------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------

if __name__ == "__main__":

    print("\n" + "=" * 80)
    print("RESEARCH AGENT")
    print("=" * 80)

    answer = run_research(
        query="Give me the current stock performance and major risk factors.",
        ticker="AAPL",
    )

    print(answer)